### ISSUE TITLE
CentOS一键魔改bbr加速搬瓦工shadowsocksr教程 | Xratzh's Site

### ISSUE THREAD

**Issue by quentin-chen** [quentin-chen/reading#60]
<b>CentOS&#19968;&#38190;&#39764;&#25913;bbr&#21152;&#36895;&#25644;&#29926;&#24037;shadowsocksr&#25945;&#31243; | Xratzh's Site</b><br>
&#27426;&#36814;&#32852;&#31995;&#25105; QQ2602995059 &#21512;&#31199;&#65288;&#26376;&#20184;10RMB&#65289;&#65292;&#36895;&#24230;&#27604;&#29926;&#24037;&#24555;&#65292;&#20215;&#26684;&#27604;&#29926;&#24037;&#20415;&#23452;&#12290; &#26412;&#24086;&#25552;&#20379;&#30340;&#20869;&#23481;&#26159;KVM&#21152;&#36895;&#25945;&#31243;&#65292;openvz&#21152;&#36895;&#30475;&#36825;&#37324;&#65306; openvz&#20248;&#21270;&#21152;&#36895; &#65306; &#25512;&#33616; &#37197;&#32622;&#31995;&#32479; &#39764;&#25913;bbr&#21152;&#36895; &#35013;SSR &#38450;&#28779;&#22681;&#65288;&#21487;&#36873; &#20999;&#25442;&#26426;&#25151; &#19979;&#36733;&#23458;&#25143;&#31471; &#25512;&#33616;&hellip;<br>
<br>
January 24, 2018 at 10:44AM<br>
via Instapaper http://ift.tt/2GdbOcG

**Comment by sblig** [comment]
http://27yun.vip/aff.php?aff=55
偶然遇见，挺方便的
